spring:
  application:
    name: msclientes
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.170:3306/springdb
    username: admin
    password: admin
    jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
      hibernate.ddl-auto: update
      generate-ddl: true
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}