spring:
  application:
    name: msclientes
# Configurações do banco de dados MySQL
  datasource:
    url: jdbc:mysql://192.168.0.170:3306/springdb
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver

# Configuração do JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@${EUREKA_SERVER}:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/logs-file.log